"""Versioned IAM PostgreSQL migration catalog and runner."""

from .catalog import (
    IAM_MIGRATION_LAYOUT,
    IAM_REVIEWED_MANIFEST_SHA256,
    MigrationArtifact,
    MigrationCatalog,
    MigrationCatalogError,
    MigrationDescriptor,
    MigrationPhase,
)
from .psycopg_adapter import (
    PsycopgMigrationAdapterUnavailable,
    PsycopgMigrationDriver,
    PsycopgMigrationSession,
    PsycopgMigrationSettings,
)
from .runner import (
    IAM_MAX_APP_COMPATIBLE_VERSION,
    IAM_MIGRATION_LOCK,
    IAM_MIGRATION_SCHEMA_ROLE,
    IAM_MIGRATION_SESSION_ROLE,
    IAM_MIN_APP_COMPATIBLE_VERSION,
    IAM_POSTGRES_MAJOR,
    IAM_SCHEMA_HEAD_VERSION,
    IamContractParameters,
    IamContractSources,
    IamMigrationRunner,
    MigrationCommitOutcomeUnknown,
    MigrationConnectionLost,
    MigrationDatabaseState,
    MigrationDriver,
    MigrationLedgerRecord,
    MigrationRunReport,
    MigrationRunnerError,
    MigrationSession,
)

__all__ = (
    "IAM_MIGRATION_LAYOUT",
    "IAM_REVIEWED_MANIFEST_SHA256",
    "IAM_MAX_APP_COMPATIBLE_VERSION",
    "IAM_MIGRATION_LOCK",
    "IAM_MIGRATION_SCHEMA_ROLE",
    "IAM_MIGRATION_SESSION_ROLE",
    "IAM_MIN_APP_COMPATIBLE_VERSION",
    "IAM_POSTGRES_MAJOR",
    "IAM_SCHEMA_HEAD_VERSION",
    "IamContractParameters",
    "IamContractSources",
    "IamMigrationRunner",
    "MigrationArtifact",
    "MigrationCatalog",
    "MigrationCatalogError",
    "MigrationCommitOutcomeUnknown",
    "MigrationConnectionLost",
    "MigrationDatabaseState",
    "MigrationDescriptor",
    "MigrationDriver",
    "MigrationLedgerRecord",
    "MigrationPhase",
    "MigrationRunReport",
    "MigrationRunnerError",
    "MigrationSession",
    "PsycopgMigrationAdapterUnavailable",
    "PsycopgMigrationDriver",
    "PsycopgMigrationSession",
    "PsycopgMigrationSettings",
)
