"""Authenticated Profile/Demand editable-workspace vertical slice."""

from .contracts import (
    EditorChoiceFieldDto,
    EditorChoiceOptionDto,
    EditorChoicesDto,
    EditorConfigurationDto,
    EditorFindingDto,
    EditorPrincipal,
    EditorReviewAssignmentDto,
    EditorReviewClaimDto,
    EditorReviewHistoryItemDto,
    EditorReviewHistoryPageDto,
    EditorReviewQueueItemDto,
    EditorResourceDto,
    EditorServiceError,
    EditorSubmissionDto,
    EditorTaxonomyBundleDto,
    EditorVersionDto,
    EditorWorkspaceSummary,
)
from .choices import build_internal_sandbox_editor_choices
from .content_choices import (
    internal_sandbox_editor_choices,
    normalize_editor_choice_path,
    validate_editor_choice_membership,
)
from .http import EditorHttpApi, HttpRequest, HttpResponse
from .asgi import EditorAsgiApplication
from .repository import MemoryEditorRepository
from .postgres import (
    DemandCompletedReleaseReplayError,
    DemandCompletedReleaseReplayProbeRequest,
    DemandCompletedReleaseReplayResult,
    DemandCompletedVerifyReplayError,
    DemandCompletedVerifyReplayProbeRequest,
    DemandCompletedVerifyReplayResult,
    DemandReadAuthority,
    EditorPostgresConfigurationError,
    EditorPsycopgConnectionSettings,
    ProfileCompletedLifecycleReplayError,
    ProfileCompletedLifecycleReplayProbeRequest,
    ProfileCompletedLifecycleReplayResult,
    ProfileReadAuthority,
    PsycopgEditorConnectionSource,
    PsycopgEditorRepository,
    PsycopgDemandCompletedVerifyReceiptProbe,
    PsycopgProfileCompletedLifecycleReceiptProbe,
)
from .service import EditorService
from .evidence import PortBackedEditorEvidenceProvider
from .sandbox_evidence import InternalSandboxEditorEvidenceProvider
from .authority import PostgresEditorAuthorityProvider
from .postgres_service import (
    DefaultEditorFieldCodeResolver,
    EditorDemandCompletedVerifyReceiptProbe,
    EditorProfileCompletedLifecycleReceiptProbe,
    EditorPostgresAuthorityProvider,
    EditorPostgresEvidenceProvider,
    EditorPostgresKeys,
    PostgresEditorService,
)
from .review_queue import (
    DemandReviewClaimRequest,
    DemandReviewQueueCommitOutcomeUnknownError,
    DemandReviewQueueError,
    PsycopgDemandReviewQueue,
)

__all__ = [
    "EditorChoiceFieldDto",
    "EditorChoiceOptionDto",
    "EditorChoicesDto",
    "EditorConfigurationDto",
    "EditorFindingDto",
    "EditorAsgiApplication",
    "EditorHttpApi",
    "EditorPostgresConfigurationError",
    "EditorPsycopgConnectionSettings",
    "EditorPrincipal",
    "EditorReviewAssignmentDto",
    "EditorReviewClaimDto",
    "EditorReviewHistoryItemDto",
    "EditorReviewHistoryPageDto",
    "EditorReviewQueueItemDto",
    "EditorPostgresAuthorityProvider",
    "EditorDemandCompletedVerifyReceiptProbe",
    "EditorProfileCompletedLifecycleReceiptProbe",
    "EditorPostgresEvidenceProvider",
    "EditorPostgresKeys",
    "EditorResourceDto",
    "EditorService",
    "EditorServiceError",
    "EditorSubmissionDto",
    "EditorTaxonomyBundleDto",
    "EditorVersionDto",
    "EditorWorkspaceSummary",
    "HttpRequest",
    "HttpResponse",
    "MemoryEditorRepository",
    "DemandCompletedVerifyReplayError",
    "DemandCompletedVerifyReplayProbeRequest",
    "DemandCompletedVerifyReplayResult",
    "DemandCompletedReleaseReplayError",
    "DemandCompletedReleaseReplayProbeRequest",
    "DemandCompletedReleaseReplayResult",
    "DemandReadAuthority",
    "ProfileCompletedLifecycleReplayError",
    "ProfileCompletedLifecycleReplayProbeRequest",
    "ProfileCompletedLifecycleReplayResult",
    "ProfileReadAuthority",
    "PsycopgEditorRepository",
    "PsycopgEditorConnectionSource",
    "PsycopgDemandCompletedVerifyReceiptProbe",
    "PsycopgProfileCompletedLifecycleReceiptProbe",
    "PostgresEditorService",
    "PortBackedEditorEvidenceProvider",
    "InternalSandboxEditorEvidenceProvider",
    "PostgresEditorAuthorityProvider",
    "DefaultEditorFieldCodeResolver",
    "DemandReviewClaimRequest",
    "DemandReviewQueueCommitOutcomeUnknownError",
    "DemandReviewQueueError",
    "PsycopgDemandReviewQueue",
    "build_internal_sandbox_editor_choices",
    "internal_sandbox_editor_choices",
    "normalize_editor_choice_path",
    "validate_editor_choice_membership",
]
